version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nestjs_api_prod
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SHOP_KEY=${SHOP_KEY}
      - WEBHOOK_IP_WHITELIST=${WEBHOOK_IP_WHITELIST}
      - WEBHOOK_ROUTE=${WEBHOOK_ROUTE}
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/seed.js &&
        node dist/main"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres_prod
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_data_prod:
