export enum ErrorCode {
  DATABASE_ERROR = 'DATABASE_ERROR',
  API_ERROR = 'API_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
}

export enum ErrorType {
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
}
